apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-repair-controller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]

# Explains