apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-repair-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-repair-controller
subjects:
- kind: ServiceAccount
  name: auto-repair-controller
  namespace: auto-repair-controller


# Explains
