apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-repair-controller
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-repair-controller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-repair-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-repair-controller
subjects:
- kind: ServiceAccount
  name: auto-repair-controller
  namespace: kube-system

# --- 

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: auto-repair-controller
#   name: auto-repair-controller
#   namespace: kube-system
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: auto-repair-controller
#   strategy: {}
#   template:
#     metadata:
#       labels:
#         app: auto-repair-controller
#     spec:
#       # imagePullSecrets:
#       # - name: regcred
#       containers:
#         - image: registry.fke.fptcloud.com/xplat-fke/auto-repair-controller:v1.0.3
#           name: auto-repair-controller
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "50m"
#             limits:
#               memory: "128Mi"
#               cpu: "200m"
#       serviceAccountName: auto-repair-controller
# # Explains
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-repair-controller
  name: auto-repair-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-repair-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: auto-repair-controller
    spec:
      nodeSelector: 
        node-role.kubernetes.io/master: ""
      containers:
        - image: registry.fke.fptcloud.com/xplat-fke/auto-repair-controller:v1.0.3
          name: auto-repair-controller
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      serviceAccountName: auto-repair-controller
