apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-repair-controller
  name: auto-repair-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-repair-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: auto-repair-controller
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
        - image: registry.fke.fptcloud.com/xplat-fke/auto-repair-controller:v1.0.0
          name: auto-repair-controller
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      serviceAccountName: auto-repair-controller
# Explains
